In [1]:
import pandas as pd
import numpy as np
import yaml
import os
from pyhive import presto # or import hive
import shutil
import math
import pickle
import matplotlib.pyplot as plt
import requests
%matplotlib inline

In [2]:
# config file for connecting to presto
config = yaml.safe_load(open(os.path.expanduser('~/config.yml')))
conn = presto.connect(**config.get('presto'))
cursor = conn.cursor()

In [3]:
cursor.execute("""
select * from searchml.rec_u_jl_rating
""")

df = pd.DataFrame(cursor.fetchall())

In [4]:
df.columns = [desc[0] for desc in cursor.description]

In [5]:
print(df.columns)

Index(['u_id', 'job_listing_id', 'rating', 'interaction'], dtype='object')


In [6]:
user_id = list(df.u_id.unique())
job_listing_ids = list(df.job_listing_id.unique())
print(len(user_id))
print(len(job_listing_ids))

13807
7750


In [27]:
RR=df.pivot_table(index='u_id',columns='job_listing_id', values='rating')


job_listing_id                        743104840   790272111   828717380   \
u_id                                                                       
00036c95-84f8-4b80-b602-de8de350d532        -1.0        -1.0        -1.0   
003e7e8f-0517-4e99-b5a2-4f86e9e8f558        -1.0        -1.0        -1.0   
007c58ba-cdd0-49fe-afc8-1de51ce41e4b        -1.0        -1.0        -1.0   
009dbe67-8844-4c28-912f-f7416b7416a7        -1.0        -1.0        -1.0   
00c50dec-5321-4a47-9d92-eaf37b9c9b67        -1.0        -1.0        -1.0   
00e2e163-696f-4ddc-b6a2-d3b915c76003        -1.0        -1.0        -1.0   
0133c3a1-d134-4eb9-8aa1-017328c96955        -1.0        -1.0        -1.0   
01d57f62-fc0e-4474-b834-4a7bbbe2401e        -1.0        -1.0        -1.0   
0200358b-afce-4a90-8615-ca80a325cca1        -1.0        -1.0        -1.0   
02059757-f98b-48ce-9836-1b5da5cba578        -1.0        -1.0        -1.0   
0228e66b-30ee-435c-b322-394701ff6c46        -1.0        -1.0        -1.0   
0249d884-6c4d-4830-af4f-5fffafcc8c9d        -1.0        -1.0        -1.0   
02a51c6e-3541-42c7-ae22-d2e0ef01fc49        -1.0        -1.0        -1.0   
02e90689-4c42-47ec-aaad-f46c060b11b6        -1.0        -1.0        -1.0   
02f4c48d-1965-458d-b3b6-d0e762366bf4        -1.0        -1.0        -1.0   
03398e92-2d0b-446f-92f3-0d11b9a1f10c        -1.0        -1.0        -1.0   
03532e9b-da08-4ff5-b355-8619550fdaa9        -1.0        -1.0        -1.0   
035fbb20-3bed-40aa-8304-2c1cb8588fab        -1.0        -1.0        -1.0   
0389c59d-fbe4-433f-8e08-841fa874ae48        -1.0        -1.0        -1.0   
03ff62ff-837e-4d48-a883-ee8d0f0c468f        -1.0        -1.0        -1.0   
04262539-ce7c-4e4a-b871-cfa53ec505ea        -1.0        -1.0        -1.0   
043173ca-c866-4dce-9e34-3cf858ade068        -1.0        -1.0        -1.0   
044fbb63-f2a8-45fd-ae3a-1facb025e4e2        -1.0        -1.0        -1.0   
0451ab38-6621-4d86-ad29-d8d091a7dae1        -1.0        -1.0        -1.0   
048ba2f4-cfff-4dee-9c27-8e9920c08b75        -1.0        -1.0        -1.0   
0490543a-f4aa-4c69-950f-16947989b088        -1.0        -1.0        -1.0   
05297c62-d5b4-4df9-b6db-65421f295b9b        -1.0        -1.0        -1.0   
053aa515-8341-495e-9911-10d3092a5042        -1.0        -1.0        -1.0   
0557b7d9-e12d-4072-a5c3-366506daaf8e        -1.0        -1.0        -1.0   
05ccd376-7307-44e7-a99e-3df96bf6711a        -1.0        -1.0        -1.0   
...                                          ...         ...         ...   
faa15d71-db3a-4160-955f-b694b49f240c        -1.0        -1.0        -1.0   
faa8bd44-8363-4155-945c-fb0f9c08c3da        -1.0        -1.0        -1.0   
fb6824a0-dadf-4728-b983-68e79ce865e3        -1.0        -1.0        -1.0   
fba2822a-a994-4720-b0e9-808efc204922        -1.0        -1.0        -1.0   
fbd38621-b45e-4f66-9a58-06a77917fea0        -1.0        -1.0        -1.0   
fc02ddfe-3f05-44c4-ae87-6cd2a633a937        -1.0        -1.0        -1.0   
fc480e25-ed35-4102-b5af-704cdd04eb77        -1.0        -1.0        -1.0   
fc602e7c-7997-4122-a645-a31a579c39de        -1.0        -1.0        -1.0   
fc65c20c-da66-429b-bdd5-58ab13a04379        -1.0        -1.0        -1.0   
fc7b192c-04b3-4a68-8d3b-16ab9a101d86        -1.0        -1.0        -1.0   
fc7eb67b-53cb-47d6-b6f6-75b7ff20ebde        -1.0        -1.0        -1.0   
fcf697ec-1baa-47ac-b649-3ab20abc38e4        -1.0        -1.0        -1.0   
fd2954ea-2ea7-401f-88ed-79a49fdabe3c        -1.0        -1.0        -1.0   
fd7b9317-0883-4525-9ac1-6736dbc045b4        -1.0        -1.0        -1.0   
fd9dae68-14b7-4410-a0b8-6c94866394ec        -1.0        -1.0        -1.0   
fdac48dc-a842-4c96-8ac6-4c2a197c96ea        -1.0        -1.0        -1.0   
fddb0874-6efb-4b39-8b24-a434f55bd9a8        -1.0        -1.0        -1.0   
fe2e6681-f43a-43f9-bddc-f6f3385ec27e        -1.0        -1.0        -1.0   
fe3128f4-fb8e-4165-8684-50e244121767        -1.0        -1.0        -1.0   
fe4e9b3a-ca06-4d63-9190-f1d94a810742        -1.0

In [28]:
print(RR.shape)


(13807, 7750)


In [35]:
RR = RR.fillna(-1)
R = RR.to_numpy()


In [36]:
print(R)

[[-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]]


In [37]:
from mf import *

In [38]:
mf = MF(R, K=2, alpha=0.1, beta=0.01, iterations=10)

In [39]:
training_process = mf.train()

Iteration: 10 ; error = 18660.1926
Iteration: 20 ; error = 19041.7671


In [40]:
print("P x Q:")
print(mf.full_matrix())
print("----------")
print("Global bias:")
print(mf.b)
print("----------")
print("User bias:")
print(mf.b_u)
print("----------")
print("Item bias:")
print(mf.b_i)

P x Q:
[[ 1.02000307  1.01279463  1.05439165 ...  0.80186156  1.01204165
   1.00392515]
 [ 0.77830835  0.96680872  0.63531018 ...  0.92274393  0.94607632
   0.92231542]
 [ 0.60646097  0.98650865  0.48636964 ...  1.02954097  0.98415534
   0.94211119]
 ...
 [ 0.64617714  0.94430481  0.84974346 ...  0.82075423  0.99845637
   0.9591895 ]
 [ 0.63762466  1.00985262  0.45606392 ...  1.07280812  0.99506435
   0.9546819 ]
 [-0.3401259   0.32353455 -0.25782232 ...  0.43018048  0.38091463
   0.30925205]]
----------
Global bias:
-0.9982393741862302
----------
User bias:
[0.79725415 0.74665109 0.79211837 ... 0.79028376 0.80508136 0.19326094]
----------
Item bias:
[0.99960313 1.20390245 0.93875579 ... 1.13589127 1.20017847 1.17369596]
